apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: 741053355470.dkr.ecr.ap-south-1.amazonaws.com/demo:main-c50158a8c248b976289551556d53d0ff2c3cc7b4
        ports:
        - containerPort: 8080
