apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node
spec:
  rules:
  - host: nodetest.mediacloud.ga
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: httpbin
            port:
              number: 80